### ISSUE TITLE
problem vcf format with 

### ISSUE THREAD

**Issue by mrouard** [SouthGreenPlatform/VcfHunter#2]
Hello,

For some reasons, VCF filtered by GATK v4 may produce a different tag by adding the assembly information next to the contig size.
`##contig=<ID=mito8,length=456355,assembly=Musa_genomes_V2.fasta>`

Then this error occurs as the scripts expects only a integer

`
Traceback (most recent call last):
  File "vcf2allPropAndCov.py", line 375, in <module>
    if __name__ == "__main__": __main__()
  File "vcf2allPropAndCov.py", line 338, in __main__
    chr_info = get_chr_size(data)
  File "vcf2allPropAndCov.py", line 220, in get_chr_size
    return [split_on_eq[2].split(',')[0], int(split_on_eq[3])]
ValueError: invalid literal for int() with base 10: '456355,assembly'
`

**Comment by guiguimartin** [comment]
We modified the code so that there should be no problems now. Could you try and verify that it works now?
And sorry for the delay in response...
