### ISSUE TITLE
VcfPreFilter.1.0.py

### ISSUE THREAD

**Issue by pbreeder** [SouthGreenPlatform/VcfHunter#5]
I got the following error, when I am running the my vcf:

python3 VcfPreFilter.1.0.py -v M301.A.sorted.MD.vcf -m 8 -M 200 -f 0.05 -c 3 -o M301.A.sorted.MD.preFiltred -d y
Traceback (most recent call last):
  File "VcfPreFilter.1.0.py", line 282, in <module>
    if __name__ == "__main__": __main__()
  File "VcfPreFilter.1.0.py", line 257, in __main__
    for line in file:
  File "/home/harun/anaconda3/envs/Env1/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 6866: invalid start byte

Thanks

**Comment by pbreeder** [comment]
I solved the reason of the problem utf-8 (language specific character in the vcf header), I found :)
